name: CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      # Checkout the codebase.
      - uses: actions/checkout@v2
      # Setup the node environment.
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Setup the repo dependencies.
      - name: Install Dependencies
        run: yarn install
      # Prepack
      - name: Prepack
        run: yarn workspace sdp-handlers prepack
      # Run the verify steps.
      - name: Test
        run: yarn test
      - name: Format
        run: yarn format
      - name: Lint
        run: yarn lint
